package system

// LXD server certificate lifecycle for InterLink trust.
//
// Two problems addressed here, both surfaced when reconfiguring InterLink with
// a freshly-installed peer:
//
//  1. LXD's stock server cert (generated by `lxd init`) only includes
//     `<hostname>, 127.0.0.1, ::1` in its Subject Alternative Names. When a
//     peer dials https://<public-ip>:8444 the TLS handshake fails with
//     "certificate is valid for 127.0.0.1, ::1, not <public-ip>".
//
//  2. Modern lxc CLIs no longer honor `skip_tls_verify: true` for self-signed
//     servers. The remote must pin the peer's server cert in the
//     `<lxd-config-dir>/servercerts/<remote-name>.crt` file or the connection
//     fails with "certificate signed by unknown authority".
//
// Both fixes run on every `LXDSyncInterlinkTrustForPeer` invocation so that
// reconfiguring InterLink with a freshly-rebuilt peer self-heals the trust.

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/sha256"
	"crypto/tls"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/hex"
	"encoding/pem"
	"fmt"
	"math/big"
	"net"
	"os"
	"os/exec"
	"os/user"
	"path/filepath"
	"strings"
	"time"
)

const lxdServerCertPath = "/var/lib/incus/server.crt"
const lxdServerKeyPath = "/var/lib/incus/server.key"

// defaultRouteIface returns the name of the interface used by the default IPv4
// route. This is the most reliable signal of "the address peers reach us on".
// Returns "" if no default route is found.
func defaultRouteIface() string {
	out, err := exec.Command("ip", "-4", "route", "show", "default").Output()
	if err != nil {
		return ""
	}
	for _, line := range strings.Split(string(out), "\n") {
		fields := strings.Fields(line)
		// "default via <gw> dev <iface> ..."
		for i, f := range fields {
			if f == "dev" && i+1 < len(fields) {
				return fields[i+1]
			}
		}
	}
	return ""
}

// localPublicIPs returns the IP(s) suitable for inclusion in the LXD server
// cert's SAN — i.e. the addresses peers will actually connect to.
//
// Strategy: prefer the address(es) on the interface that carries the default
// route. That's the public address by definition. Fall back to a filtered
// scan if the default-route interface can't be determined (e.g. unusual
// netplan/policy-routing setups).
//
// LXD-managed bridges (host-nat, lxdbr*, lxcbr*) and other internal bridges
// (virbr*, docker*, veth*, tap*) are excluded from the fallback so we never
// pin core.https_address to an internal IP. Down interfaces are also skipped.
func localPublicIPs() []net.IP {
	skipPrefixes := []string{"lxdbr", "lxcbr", "virbr", "docker", "veth", "tap"}
	// host-nat, host-nat2, … are all ours and all internal — see
	// IsHostNatNetwork. Matching only the bare name would let host-nat2's
	// private address be picked as the server's public IP.
	skipExact := map[string]bool{}

	ifaces, err := net.Interfaces()
	if err != nil {
		return nil
	}

	// Preferred: walk the default-route interface only.
	if defIface := defaultRouteIface(); defIface != "" {
		for _, iface := range ifaces {
			if iface.Name != defIface {
				continue
			}
			if iface.Flags&net.FlagUp == 0 {
				break
			}
			return ipsOf(iface)
		}
	}

	// Fallback: every up, non-loopback, non-internal-bridge interface.
	var out []net.IP
	for _, iface := range ifaces {
		if iface.Flags&net.FlagLoopback != 0 {
			continue
		}
		if iface.Flags&net.FlagUp == 0 {
			continue // skip DOWN interfaces — their IPs aren't reachable
		}
		if skipExact[iface.Name] || IsHostNatNetwork(iface.Name) {
			continue
		}
		skip := false
		for _, p := range skipPrefixes {
			if strings.HasPrefix(iface.Name, p) {
				skip = true
				break
			}
		}
		if skip {
			continue
		}
		out = append(out, ipsOf(iface)...)
	}
	return out
}

// ipsOf returns the non-link-local IPs assigned to an interface.
func ipsOf(iface net.Interface) []net.IP {
	addrs, _ := iface.Addrs()
	var out []net.IP
	for _, a := range addrs {
		ip, _, err := net.ParseCIDR(a.String())
		if err != nil {
			continue
		}
		if ip.IsLinkLocalUnicast() || ip.IsLinkLocalMulticast() {
			continue
		}
		out = append(out, ip)
	}
	return out
}

// readLXDServerCert reads the live LXD server.crt; returns the parsed cert.
func readLXDServerCert() (*x509.Certificate, error) {
	// /var/lib/incus/server.crt is mode 0644 root-owned, world-readable in
	// practice, but on some installs it isn't traversable as zfsnas. Try a
	// direct read first, fall back to "sudo cat".
	data, err := os.ReadFile(lxdServerCertPath)
	if err != nil {
		out, sudoErr := exec.Command("sudo", "cat", lxdServerCertPath).Output()
		if sudoErr != nil {
			return nil, fmt.Errorf("read %s: %w", lxdServerCertPath, err)
		}
		data = out
	}
	block, _ := pem.Decode(data)
	if block == nil {
		return nil, fmt.Errorf("no PEM block in %s", lxdServerCertPath)
	}
	return x509.ParseCertificate(block.Bytes)
}

// certCoversIPs reports whether cert's SAN list already contains every IP in
// want. Used to decide whether a regen is needed.
func certCoversIPs(cert *x509.Certificate, want []net.IP) bool {
	have := map[string]bool{}
	for _, ip := range cert.IPAddresses {
		have[ip.String()] = true
	}
	for _, ip := range want {
		if !have[ip.String()] {
			return false
		}
	}
	return true
}

// LXDEnsureServerCertSAN regenerates /var/lib/incus/server.{crt,key} when the
// existing cert is missing any of the host's public IPs in its SAN. No-op
// when the cert is already complete. Requires root or unrestricted sudo
// (NOPASSWD: ALL); under hardened sudoers it logs a warning and returns nil
// so InterLink trust sync can continue with whatever cert is in place.
func LXDEnsureServerCertSAN() error {
	cert, err := readLXDServerCert()
	if err != nil {
		// LXD not initialised yet — nothing to do.
		return nil
	}
	want := localPublicIPs()
	if certCoversIPs(cert, want) {
		return nil
	}

	mode := CheckSudoAccess().Type
	if mode != "root" && mode != "all" {
		fmt.Printf("lxd cert: server cert is missing public-IP SANs but the portal lacks the privileges to regenerate it (sudo mode = %q). Run as root or with NOPASSWD: ALL once to self-heal.\n", mode)
		return nil
	}

	// Generate ECDSA P-384 cert (matches LXD's own format).
	priv, err := ecdsa.GenerateKey(elliptic.P384(), rand.Reader)
	if err != nil {
		return fmt.Errorf("generate ECDSA key: %w", err)
	}
	hostname, _ := os.Hostname()
	if hostname == "" {
		hostname = "lxd"
	}
	serial, _ := rand.Int(rand.Reader, new(big.Int).Lsh(big.NewInt(1), 128))

	// SAN = hostname + loopback + all public interface IPs (deduped).
	ipSet := map[string]net.IP{}
	for _, ip := range want {
		ipSet[ip.String()] = ip
	}
	ipSet["127.0.0.1"] = net.ParseIP("127.0.0.1")
	ipSet["::1"] = net.ParseIP("::1")
	var ips []net.IP
	for _, ip := range ipSet {
		ips = append(ips, ip)
	}

	template := &x509.Certificate{
		SerialNumber: serial,
		Subject: pkix.Name{
			CommonName:   hostname,
			Organization: []string{"LXD"},
		},
		NotBefore:             time.Now().Add(-time.Minute),
		NotAfter:              time.Now().Add(10 * 365 * 24 * time.Hour),
		KeyUsage:              x509.KeyUsageDigitalSignature | x509.KeyUsageKeyEncipherment | x509.KeyUsageCertSign,
		ExtKeyUsage:           []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth, x509.ExtKeyUsageClientAuth},
		BasicConstraintsValid: true,
		IsCA:                  true,
		DNSNames:              []string{hostname},
		IPAddresses:           ips,
	}

	certDER, err := x509.CreateCertificate(rand.Reader, template, template, &priv.PublicKey, priv)
	if err != nil {
		return fmt.Errorf("create certificate: %w", err)
	}
	keyDER, err := x509.MarshalECPrivateKey(priv)
	if err != nil {
		return fmt.Errorf("marshal key: %w", err)
	}
	certPEM := pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: certDER})
	keyPEM := pem.EncodeToMemory(&pem.Block{Type: "EC PRIVATE KEY", Bytes: keyDER})

	// Stop LXD, replace files, start LXD. Use sudo paths so this works for
	// the zfsnas service account under sudo-all.
	if err := runRootShell("systemctl stop lxd lxd.socket || true"); err != nil {
		return fmt.Errorf("stop lxd: %w", err)
	}
	if err := writeRootFile(lxdServerCertPath, certPEM, 0644); err != nil {
		return fmt.Errorf("write server.crt: %w", err)
	}
	if err := writeRootFile(lxdServerKeyPath, keyPEM, 0600); err != nil {
		return fmt.Errorf("write server.key: %w", err)
	}
	if err := runRootShell("systemctl start lxd.socket && systemctl start lxd"); err != nil {
		return fmt.Errorf("start lxd: %w", err)
	}
	// Give LXD a moment to come back before downstream calls hit it.
	for i := 0; i < 20; i++ {
		if exec.Command("incus", "info").Run() == nil {
			break
		}
		time.Sleep(time.Second)
	}
	fmt.Printf("lxd cert: regenerated server cert with SAN IPs=%v hostname=%q\n", ips, hostname)
	return nil
}

// runRootShell runs a shell command as root. Uses the host shell directly when
// already root, otherwise sudo bash -c. Caller is responsible for command
// being idempotent / safe.
func runRootShell(cmd string) error {
	if os.Getuid() == 0 {
		return exec.Command("/bin/bash", "-c", cmd).Run()
	}
	return exec.Command("sudo", "/bin/bash", "-c", cmd).Run()
}

// writeRootFile writes data to a root-owned path with the given mode. Uses
// direct I/O when running as root, otherwise pipes through sudo tee + sudo
// chmod.
func writeRootFile(path string, data []byte, mode os.FileMode) error {
	if os.Getuid() == 0 {
		return os.WriteFile(path, data, mode)
	}
	cmd := exec.Command("sudo", "/usr/bin/tee", path)
	cmd.Stdin = strings.NewReader(string(data))
	cmd.Stdout = nil
	if out, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("tee %s: %s", path, strings.TrimSpace(string(out)))
	}
	if err := exec.Command("sudo", "/usr/bin/chmod", fmt.Sprintf("%04o", mode), path).Run(); err != nil {
		return fmt.Errorf("chmod %s: %w", path, err)
	}
	return nil
}

// LXDFetchPeerServerCert opens a TLS connection to host:8444 and returns the
// leaf server cert as PEM. Skips verification (the cert is precisely what we
// want to fetch and pin) — safe because the surrounding InterLink flow already
// authenticated the peer via HMAC.
func LXDFetchPeerServerCert(host string) (string, error) {
	addr := host
	if !strings.Contains(addr, ":") {
		addr = host + ":8444"
	}
	d := &net.Dialer{Timeout: 5 * time.Second}
	conn, err := tls.DialWithDialer(d, "tcp", addr, &tls.Config{InsecureSkipVerify: true})
	if err != nil {
		return "", fmt.Errorf("tls dial %s: %w", addr, err)
	}
	defer conn.Close()
	chain := conn.ConnectionState().PeerCertificates
	if len(chain) == 0 {
		return "", fmt.Errorf("no peer cert presented by %s", addr)
	}
	block := pem.Block{Type: "CERTIFICATE", Bytes: chain[0].Raw}
	return string(pem.EncodeToMemory(&block)), nil
}

// LXDPinPeerServerCert writes the peer's server cert PEM to the lxc CLI's
// servercerts directory. Without this the lxc CLI rejects the self-signed peer
// cert with "x509: certificate signed by unknown authority" — the
// `skip_tls_verify` flag in the remote's config is no longer honored on
// modern LXD (it's accepted as legal config but ignored at runtime).
func LXDPinPeerServerCert(remoteName, certPEM string) error {
	dir := filepath.Join(lxdConfigDir(), "servercerts")
	if err := os.MkdirAll(dir, 0700); err != nil {
		return fmt.Errorf("mkdir %s: %w", dir, err)
	}
	path := filepath.Join(dir, remoteName+".crt")
	if err := os.WriteFile(path, []byte(certPEM), 0644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	// Match ownership to the zfsnas service user so the lxc CLI invoked by
	// the portal (which runs as zfsnas) can read it.
	if u, err := user.Lookup("zfsnas"); err == nil {
		var uid, gid int
		fmt.Sscanf(u.Uid, "%d", &uid)
		fmt.Sscanf(u.Gid, "%d", &gid)
		os.Lchown(dir, uid, gid)  //nolint:errcheck
		os.Lchown(path, uid, gid) //nolint:errcheck
	}
	return nil
}

// LXDPinSelfHTTPSAddress sets core.https_address to <publicIP>:8444 (when not
// already set to a specific address). Wildcard listeners cause LXD to advertise
// every local IP — including internal bridge addresses — to migration peers,
// who then waste time dialing unreachable addresses before falling back to the
// public one. Pinning the listener to the public IP eliminates that.
// Best-effort: errors are logged but never fatal.
func LXDPinSelfHTTPSAddress() {
	out, err := exec.Command("incus", "config", "get", "core.https_address").Output()
	if err != nil {
		return
	}
	cur := strings.TrimSpace(string(out))
	// Already set to a specific (non-wildcard) host:port — leave it alone.
	if cur != "" && !strings.HasPrefix(cur, ":") && !strings.HasPrefix(cur, "[::]") &&
		!strings.HasPrefix(cur, "0.0.0.0") {
		return
	}
	for _, ip := range localPublicIPs() {
		if ip.To4() == nil {
			continue // pin IPv4 only — most peers reach via v4
		}
		addr := ip.String() + ":8444"
		if err := exec.Command("incus", "config", "set", "core.https_address", addr).Run(); err != nil {
			fmt.Printf("lxd cert: pin core.https_address to %s: %v\n", addr, err)
		}
		return
	}
}

// fingerprintHex returns the SHA-256 fingerprint of a PEM cert as lowercase
// hex without separators. Used for de-dup logic / audit logging.
func fingerprintHex(certPEM string) string {
	block, _ := pem.Decode([]byte(certPEM))
	if block == nil {
		return ""
	}
	sum := sha256.Sum256(block.Bytes)
	return hex.EncodeToString(sum[:])
}
